apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: storage-config
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-28"
spec:
  project: default
  source:
    repoURL: https://github.com/erauner12/homelab-k8s-starter.git
    targetRevision: main
    path: infrastructure/storage-config/overlays/no-longhorn
  destination:
    server: https://kubernetes.default.svc
    namespace: local-path-storage
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
