apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Cloud cluster network secrets (tunnel tokens, etc.)
resources:
  - ../../base

generators:
  - secret-generator.yaml

generatorOptions:
  disableNameSuffixHash: true
