apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - argocd-projects.yaml
  - argocd-runtime.yaml
  - sops-age-seed.yaml
  - argocd-tailscale-access.yaml
  - cilium-config.yaml
  - storage-config.yaml
