apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: exposure-demo-tailscale
  annotations:
    tailscale.com/proxy-class: "iptables-proxy"
spec:
  ingressClassName: tailscale
  defaultBackend:
    service:
      name: exposure-demo
      port:
        number: 8080
  tls:
    - hosts:
        - exposure-demo
