apiVersion: v1
kind: Service
metadata:
  name: exposure-demo
  labels:
    app: exposure-demo
spec:
  selector:
    app: exposure-demo
  ports:
    - name: http
      port: 8080
      targetPort: http
      protocol: TCP
