kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: homelab-starter
nodes:
  - role: control-plane
    extraPortMappings:
      - containerPort: 30080
        hostPort: 18080
        protocol: TCP
      - containerPort: 30443
        hostPort: 18443
        protocol: TCP
