apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Test resources for validating Tailscale operator functionality
# These are NOT automatically deployed - apply manually to test:
#   kubectl apply -k operators/tailscale-operator/test-resources/

namespace: tailscale

resources:
  - whoami-deployment.yaml
  - whoami-service-tailscale.yaml
