apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Cloud-minimal namespaces required for current DOKS baseline.
resources:
  - argocd.yaml
  - cert-manager.yaml
  - external-secrets.yaml
  - network.yaml
  - observability.yaml
  - demo.yaml
  - envoy-gateway-system.yaml
  - security.yaml
  - tailscale.yaml
