apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  labels:
    homelab.dev/layer: stack

resources:
  - deployment.yaml
  - service.yaml

commonLabels:
  app.kubernetes.io/managed-by: argocd
  homelab.dev/managed-by: argocd
