image:
  repository: cloudflare/cloudflared
  tag: 2025.11.1
  imagePullPolicy: IfNotPresent

replicaCount: 2

managed:
  enabled: true
  existingSecret: cloudflared-apps-token

local:
  enabled: false

resources:
  requests:
    cpu: 10m
    memory: 100Mi
  limits:
    memory: 100Mi
