apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - argocd-tailscale-access-app.yaml
  - cert-manager-app.yaml
  - external-dns-app.yaml
  - external-secrets-app.yaml
  - envoy-gateway-app.yaml
  - tailscale-operator-app.yaml
