apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Cloud cluster operators (explicit opt-in)
resources:
  - operators-project.yaml
  - external-secrets-app.yaml
  - cert-manager-app.yaml
