apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - cert-manager-app.yaml
  - external-dns-app.yaml
  - envoy-gateway-app.yaml
  - cloudflared-apps-app.yaml
  - tailscale-operator-app.yaml
