apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - app-of-apps-project.yaml
  - infrastructure-project.yaml
  - operators-project.yaml
  - security-project.yaml
  - apps-project.yaml
