apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Cloud cluster applications (explicit opt-in)
resources:
  - observability-project.yaml
  - giraffe-cloud-minimal-app.yaml
  - apps-project.yaml
  - whoami-app.yaml
