apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: openclaw-tailscale
  annotations:
    tailscale.com/proxy-class: "iptables-proxy"
spec:
  ingressClassName: tailscale
  defaultBackend:
    service:
      name: openclaw
      port:
        number: 18789
  tls:
    - hosts:
        - openclaw
